apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-asaiasa

resources:
  - ../../base
  - ingress.yaml


# configMapGenerator:
# - name: villagefund-pm-api-configmap
#   literals:
#   - GOAPP_HOST=0.0.0.0
#   - GOAPP_PORT=8000
#   envs:
#   - prod-config.properties

# patches:
# - path: deployment.yaml
