apiVersion: v1
kind: Service
metadata:
  name: app-asaiasa-service
spec:
  selector:
    app: web
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: redis-asaiasa-service
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379