apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: ghcr.io/mastodon/mastodon:v4.3.0
          command: ["bundle", "exec", "sidekiq"]
          envFrom:
            - configMapRef:
                name: mastodon-config
          volumeMounts:
            - mountPath: /mastodon/public/system
              name: sidekiq-data
          readinessProbe:
            exec:
              command: ["ps", "aux", "|", "grep", "[s]idekiq"]
            initialDelaySeconds: 10
            periodSeconds: 5
  volumes:
    - name: sidekiq-data
      persistentVolumeClaim:
        claimName: sidekiq-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sidekiq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
